# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 06:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavingsPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.PositiveIntegerField(default=100)),
                ('target', models.PositiveIntegerField(default=200)),
                ('deposit_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZeraPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('frequency', models.CharField(choices=[('d', 'daily'), ('w', 'weekly'), ('m', 'monthly')], max_length=1)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('send_invoices', models.BooleanField(default=False)),
                ('send_sms', models.CharField(blank=True, max_length=13, null=True)),
                ('hosted_page', models.CharField(blank=True, max_length=13, null=True)),
                ('hosted_page_url', models.URLField(null=True)),
                ('hosted_page_summary', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='usersavingsplan',
            name='freq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerasaver.ZeraPlan'),
        ),
        migrations.AddField(
            model_name='usersavingsplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
