# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerasaver', '0002_auto_20170807_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeraplan',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'daily'), (2, 'weekly'), (3, 'monthly')], default=1),
        ),
    ]
