# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerasaver', '0004_auto_20170807_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersavingsplan',
            name='freq',
        ),
        migrations.AddField(
            model_name='usersavingsplan',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'daily'), (2, 'weekly'), (3, 'monthly')], default=1),
        ),
        migrations.AddField(
            model_name='usersavingsplan',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zerasaver.ZeraPlan'),
            preserve_default=False,
        ),
    ]
