# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerasaver', '0005_auto_20170807_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavingsplan',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1),
        ),
    ]
