# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerasaver', '0006_usersavingsplan_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zeraplan',
            name='paystack_plan_id',
        ),
        migrations.AddField(
            model_name='zeraplan',
            name='pplan_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zeraplan',
            name='pplan_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zeraplan',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
