# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerasaver', '0007_auto_20170808_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeraplan',
            name='amount',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
