# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerasaver', '0010_auto_20170809_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavingsplan',
            name='day_of_month',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th'), (11, '11th'), (12, '12th'), (13, '13th'), (14, '14th'), (15, '15th'), (16, '16th'), (17, '17th'), (18, '18th'), (19, '19th'), (20, '20th'), (21, '21st'), (22, '22nd'), (23, '23rd'), (24, '24th'), (25, '25th'), (26, '26th'), (27, '27th'), (28, '28th')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='usersavingsplan',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='usersavingsplan',
            name='deposit_amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usersavingsplan',
            name='deposit_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usersavingsplan',
            name='target',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
