# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerasaver', '0011_auto_20170809_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavingsplan',
            name='pcus_code',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersavingsplan',
            name='pcus_id',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
