# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerasaver', '0014_auto_20170909_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavingsplan',
            name='target',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
