# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerasaver', '0016_auto_20170909_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavingsplan',
            name='has_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersavingsplan',
            name='psub_token',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zeraplan',
            name='hosted_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zeraplan',
            name='send_invoices',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='zeraplan',
            name='send_sms',
            field=models.BooleanField(default=True),
        ),
    ]
