# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 11:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zerasaver', '0017_auto_20170911_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='USubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('psub_id', models.PositiveIntegerField(editable=False, null=True)),
                ('psub_code', models.CharField(editable=False, max_length=100, null=True)),
                ('psub_token', models.CharField(editable=False, max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
