# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerasaver', '0018_usubscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usubscriptions',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zerasaver.ZeraPlan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usubscriptions',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usubscriptions',
            name='psub_code',
            field=models.CharField(default='x', editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usubscriptions',
            name='psub_id',
            field=models.PositiveIntegerField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usubscriptions',
            name='psub_token',
            field=models.CharField(default='x', editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
