# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerasaver', '0021_auto_20170911_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavingsplan',
            name='auth',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
