# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 22:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zerasaver', '0022_usersavingsplan_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('bank_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerasaver.WithdrawalAcc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='withdrawals',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='withdrawals',
            name='bank_details',
        ),
        migrations.RemoveField(
            model_name='withdrawals',
            name='user',
        ),
        migrations.AddField(
            model_name='withdrawals',
            name='request',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='zerasaver.WithdrawalRequest'),
            preserve_default=False,
        ),
    ]
