# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerasaver', '0023_auto_20171006_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavingsplan',
            name='time_of_day',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
