# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerasaver', '0024_usersavingsplan_time_of_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavingsplan',
            name='deposit_time',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
