# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerasaver', '0025_auto_20171007_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersavingsplan',
            name='time_of_day',
        ),
    ]
