# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerasaver', '0029_usubscriptions_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usubscriptions',
            name='psub_token',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
